version: 2.1

# Add additional CircleCI Orbs dependencies
orbs:
  # https://circleci.com/orbs/registry/orb/circleci/kubernetes
  kubernetes: circleci/kubernetes@0.3.0
  # https://circleci.com/orbs/registry/orb/circleci/helm
  helm: circleci/helm@0.1.2
  # https://circleci.com/orbs/registry/orb/ccpgames/minikube
  minikube: ccpgames/minikube@0.0.1

jobs:
  # Run Helm Lint checks
  helm-lint:
    docker:
      - image: lachlanevenson/k8s-helm
    steps:
      - checkout
      - run:
          name: Prepare Helm
          command: |
            set -x
            helm init --client-only
      - run:
          name: Helm Lint Dex
          command: helm lint charts/dex
      - run:
          name: Helm Lint Dex-K8s-Authenticator
          command: helm lint charts/dex-k8s-authenticator
      - run:
          name: Helm template
          command: |
            mkdir -p dex dex-k8s-authenticator
            helm template --output-dir /tmp/charts/dex charts/dex
            helm template --output-dir /tmp/charts/dex-k8s-authenticator charts/dex-k8s-authenticator
      - persist_to_workspace:
          root: /tmp/charts
          paths:
            - dex
            - dex-k8s-authenticator

  # Run Kubernetes lint checks
  k8s-lint:
    docker:
      - image: garethr/kubeval
    steps:
      - attach_workspace:
          at: .
      - run:
          name: K8s Kubeval Lint Check (dex)
          command: kubeval $(find . -type f)
          working_directory: /tmp/dex
      - run:
          name: K8s Kubeval Lint Check (dex-k8s-authenticator)
          command: kubeval $(find . -type f)
          working_directory: /tmp/dex-k8s-authenticator

  # Spin up minikube K8s cluster and run Helm chart & e2e tests on it
  helm-e2e:
    machine:
      # Available images https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - kubernetes/install
      - minikube/minikube-install:
          version: v1.2.0
      - run:
          name: Create new K8s cluster
          command: sudo -E minikube start --vm-driver=none --cpus $(nproc) --memory 4096
          environment:
            CHANGE_MINIKUBE_NONE_USER: true
      - run:
          name: Helm install dex
          command: helm install --timeout 600 --debug --wait --name dex charts/dex
      - run:
          when: always
          name: Show created K8s resources (Community)
          command: kubectl get all

workflows:
  version: 2
  helm:
    jobs:
      - helm-lint
      - k8s-lint:
          requires:
            - helm-lint
      - helm-e2e:
          requires:
            - helm-lint
            - k8s-lint

