apiVersion: v1
kind: Service
metadata:
  name: {{ template "dex.fullname" . }}
  labels:
    app: {{ template "dex.name" . }}
    env: {{ default "dev" .Values.global.deployEnv }}
    chart: {{ template "dex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: 5556
    protocol: TCP
  - name: https
    port: 443
    targetPort: 5556
    protocol: TCP

  selector:
    app: {{ template "dex.name" . }}
    release: {{ .Release.Name }}
