apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dex-k8s-authenticator.fullname" . }}
  labels:
    app: {{ template "dex-k8s-authenticator.fullname" . }}
    env: {{ default "dev" .Values.global.deployEnv }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.yaml: |-
    {{- with .Values.dexK8sAuthenticator }}
    listen: {{ if .tls.create }}https{{ else }}http{{ end }}://0.0.0.0:{{ default "5555" .port }}
    debug: {{ default "false" .debug }}
    {{- if .logoUrl }}
    logo_uri: {{ .logoUrl }}
    {{- end }}
    {{- if and .tls.create .tlsCert .tlsKey }}
    tls_cert: "/etc/dex-k8s-authenticator/tls.crt"
    tls_key: "/etc/dex-k8s-authenticator/tls.key"
    {{- end }}
    clusters:
{{ toYaml .clusters | indent 4 }}
    {{- end }}

