apiVersion: v1
kind: Service
metadata:
  name: {{ template "dex-k8s-authenticator.fullname" . }}
  labels:
    app: {{ template "dex-k8s-authenticator.name" . }}
    env: {{ default "dev" .Values.global.deployEnv }}
    chart: {{ template "dex-k8s-authenticator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web
      port: {{ default "80" .Values.service.port }}
      targetPort: {{ default "5555" .Values.dexK8sAuthenticator.port }}
      protocol: TCP
  selector:
    app: {{ template "dex-k8s-authenticator.name" . }}
    release: {{ .Release.Name }}
